# Generated by Django 2.2.26 on 2022-06-16 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev', models.CharField(max_length=200)),
                ('saved_date', models.DateTimeField(default=datetime.datetime(2022, 6, 16, 12, 59, 29, 577941))),
                ('pow', models.FloatField()),
                ('ready', models.IntegerField(default=0, null=True)),
                ('signal', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devId', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 6, 16, 12, 59, 29, 577941))),
                ('value', models.FloatField()),
                ('grid', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 6, 16, 12, 59, 29, 578938))),
                ('value', models.FloatField()),
            ],
        ),
    ]
