# Generated by Django 2.2.26 on 2022-06-17 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flexi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flexiDev', models.CharField(max_length=300)),
                ('response_time', models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 42, 7, 807054))),
                ('res_pow', models.FloatField()),
                ('res_durr', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 42, 7, 806056)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 42, 7, 805053)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 42, 7, 806056)),
        ),
    ]
