# Generated by Django 2.2.26 on 2022-06-16 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='ready',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='online',
            name='signal',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='grid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 16, 59, 20, 647038)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 16, 59, 20, 645995)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 16, 59, 20, 647038)),
        ),
    ]
