# Generated by Django 2.2.26 on 2022-06-16 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='dev',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 17, 23, 4, 557640)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 17, 23, 4, 557640)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 17, 23, 4, 558643)),
        ),
    ]
