# Generated by Django 2.2.26 on 2022-04-29 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0002_auto_20220325_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 15, 54, 2, 917693)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 15, 54, 2, 916693)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 15, 54, 2, 917693)),
        ),
    ]
