# Generated by Django 2.2.26 on 2022-06-20 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0002_auto_20220617_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='providing',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='flexi',
            name='response_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 13, 15, 16, 208857)),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 13, 15, 16, 207856)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 13, 15, 16, 206851)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 13, 15, 16, 207856)),
        ),
    ]
