# Generated by Django 2.2.26 on 2022-06-15 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0003_auto_20220429_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='ready',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='online',
            name='signal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='ready',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='signal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 13, 25, 3, 33361)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 13, 25, 3, 32358)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 13, 25, 3, 34359)),
        ),
    ]
