# Generated by Django 2.2.26 on 2022-06-15 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0004_auto_20220615_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online',
            name='ready',
        ),
        migrations.RemoveField(
            model_name='online',
            name='signal',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ready',
        ),
        migrations.RemoveField(
            model_name='post',
            name='signal',
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 13, 38, 27, 551027)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 13, 38, 27, 550017)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 13, 38, 27, 552020)),
        ),
    ]
