# Generated by Django 2.2.26 on 2022-11-02 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0005_auto_20220916_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='dev_name',
            field=models.CharField(default='lab', max_length=300),
        ),
        migrations.AddField(
            model_name='online',
            name='lat',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='online',
            name='long',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aris',
            name='timestamp_aris',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 11, 32, 53, 141039)),
        ),
        migrations.AlterField(
            model_name='flexabilitysim',
            name='scheduled',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 11, 32, 53, 141039)),
        ),
        migrations.AlterField(
            model_name='flexi',
            name='response_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 11, 32, 53, 140040)),
        ),
        migrations.AlterField(
            model_name='hydro',
            name='timestamp_hydro',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 11, 32, 53, 142039)),
        ),
        migrations.AlterField(
            model_name='neykovo',
            name='timestamp_neykovo',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 11, 32, 53, 142039)),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 11, 32, 53, 140040)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 11, 32, 53, 139039)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 11, 32, 53, 140040)),
        ),
    ]
