# Generated by Django 2.2.26 on 2022-06-15 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0006_auto_20220615_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ready',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='signal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 15, 1, 11, 300000)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 15, 1, 11, 299001)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 15, 1, 11, 300000)),
        ),
    ]
