# Generated by Django 2.2.26 on 2022-06-16 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0007_auto_20220615_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ready',
        ),
        migrations.RemoveField(
            model_name='post',
            name='signal',
        ),
        migrations.AddField(
            model_name='online',
            name='ready',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='online',
            name='signal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 10, 46, 9, 358419)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 10, 46, 9, 358419)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 10, 46, 9, 359420)),
        ),
    ]
