# Generated by Django 2.2.26 on 2022-06-16 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0008_auto_20220616_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='ready',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 10, 52, 42, 230979)),
        ),
        migrations.AlterField(
            model_name='online',
            name='signal',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 10, 52, 42, 229951)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 10, 52, 42, 230979)),
        ),
    ]
