# Generated by Django 2.2.26 on 2022-11-22 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0008_auto_20221121_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='budgetD',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='budgetH',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='budgetM',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='costD',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='costH',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='costM',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aris',
            name='timestamp_aris',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 15, 11, 46, 211789)),
        ),
        migrations.AlterField(
            model_name='flexabilitysim',
            name='scheduled',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 15, 11, 46, 211789)),
        ),
        migrations.AlterField(
            model_name='flexi',
            name='response_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 15, 11, 46, 210791)),
        ),
        migrations.AlterField(
            model_name='hydro',
            name='timestamp_hydro',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 15, 11, 46, 212788)),
        ),
        migrations.AlterField(
            model_name='neykovo',
            name='timestamp_neykovo',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 15, 11, 46, 211789)),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 15, 11, 46, 209787)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 15, 11, 46, 207789)),
        ),
        migrations.AlterField(
            model_name='postforecast',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 15, 11, 46, 208791)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 15, 11, 46, 210791)),
        ),
    ]
