# Generated by Django 2.2.26 on 2022-12-15 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0009_auto_20221122_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='actualCorr',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='actualProviding',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='providingAmount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aris',
            name='timestamp_aris',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 16, 14, 35, 488369)),
        ),
        migrations.AlterField(
            model_name='flexabilitysim',
            name='scheduled',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 16, 14, 35, 488369)),
        ),
        migrations.AlterField(
            model_name='flexi',
            name='response_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 16, 14, 35, 487370)),
        ),
        migrations.AlterField(
            model_name='hydro',
            name='timestamp_hydro',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 16, 14, 35, 489369)),
        ),
        migrations.AlterField(
            model_name='neykovo',
            name='timestamp_neykovo',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 16, 14, 35, 489369)),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 16, 14, 35, 487370)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 16, 14, 35, 486376)),
        ),
        migrations.AlterField(
            model_name='postforecast',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 16, 14, 35, 486376)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 16, 14, 35, 487370)),
        ),
    ]
