# Generated by Django 2.2.26 on 2022-06-16 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0009_auto_20220616_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='grid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 11, 16, 19, 669228)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 11, 16, 19, 668232)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 11, 16, 19, 669228)),
        ),
    ]
