# Generated by Django 2.2.26 on 2023-06-12 12:39

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0013_auto_20230517_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostForecastMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devId', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2023, 6, 12, 15, 39, 12, 541465))),
                ('value', models.FloatField()),
            ],
            managers=[
                ('today', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='aris',
            name='timestamp_aris',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 15, 39, 12, 543464)),
        ),
        migrations.AlterField(
            model_name='flexabilitysim',
            name='scheduled',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 15, 39, 12, 542464)),
        ),
        migrations.AlterField(
            model_name='flexi',
            name='response_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 15, 39, 12, 542464)),
        ),
        migrations.AlterField(
            model_name='hydro',
            name='timestamp_hydro',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 15, 39, 12, 544463)),
        ),
        migrations.AlterField(
            model_name='neykovo',
            name='timestamp_neykovo',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 15, 39, 12, 543464)),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 15, 39, 12, 541465)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 15, 39, 12, 540481)),
        ),
        migrations.AlterField(
            model_name='postforecast',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 15, 39, 12, 540481)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 15, 39, 12, 542464)),
        ),
    ]
